module.exports = {
  docs: [
    {
      // 1st Section: Display name of the sidebar
      "About Commit": [
        {
          type: 'autogenerated',
          // which physical folder this header will scan for documents
          dirName: 'about',
        },
      ],
      // 2nd Section: Display name of the sidebar
      "Application Process": [
        {
          type: 'autogenerated',
          dirName: 'application',
        },
      ],
      // 3rd Section: Display name of the sidebar
      "The EP Program": [
        {
          type: 'autogenerated',
          dirName: 'eps',
        },
      ],
       // 4th Section: Display name of the sidebar
      "Additional Resources": [
        {
          type: 'autogenerated',
          dirName: 'resources',
        },
      ],
      // Last Section: Display name of the sidebar
      "Legal": [
        {
          type: 'autogenerated',
          dirName: 'legal',
        },
      ]
    }
  ],
};
