module.exports = {
  docs: [
    {
      // Section: Display name of the sidebar
      "About": [
        {
          type: 'autogenerated',
          // which physical folder this header will scan for documents
          dirName: 'about',
        },
      ],
      // Section: Display name of the sidebar
      "Engineering Partners": [
        {
          type: 'autogenerated',
          dirName: 'eps',
        },
      ],
      "Resources": [
        {
          type: 'autogenerated',
          dirName: 'resources',
        },
      ]
    }
  ],
};
