module.exports = {
  docs: [
    {
      // 1st Section: Display name of the sidebar
      "About Commit": [
        {
          type: 'autogenerated',
          // which physical folder this header will scan for documents
          dirName: 'about',
        },
      ],
      // 2nd Section: Display name of the sidebar
      "The EP Program": [
        {
          type: 'autogenerated',
          dirName: 'eps',
        },
      ],
      // 3rd Section: Display name of the sidebar
      "EP Resources": [
        {
          type: 'autogenerated',
          dirName: 'epresources',
        },
      ],
       // 4th Section: Display name of the sidebar
      "How to Contribute": [
        {
          type: 'autogenerated',
          dirName: 'contribute',
        },
      ],
      // 5th Section: Display name of the sidebar
      "Legal": [
        {
          type: 'autogenerated',
          dirName: 'legal',
        },
      ],
      // Last Section: Display name of the sidebar
      "Other Resources": [
        {
          type: 'autogenerated',
          dirName: 'resources',
        },
      ]
    }
  ],
};
